### ISSUE TITLE
Error in Quickblox 3.3.1 login

### ISSUE THREAD

**Issue by ashutoshgohil** [QuickBlox/quickblox-android-sdk-releases#10]
Hi,

When I called qblogin in my code then I am getting this error. Please suggest me how to resolve it.

java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
                                                                   at java.util.Calendar.setTime(Calendar.java:1197)
                                                                   at java.text.SimpleDateFormat.formatImpl(SimpleDateFormat.java:527)
                                                                   at java.text.SimpleDateFormat.format(SimpleDateFormat.java:829)
                                                                   at java.text.DateFormat.format(DateFormat.java:314)
                                                                   at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:88)
                                                                   at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:40)
                                                                   at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
                                                                   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
                                                                   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
                                                                   at com.google.gson.Gson.toJson(Gson.java:669)
                                                                   at com.google.gson.Gson.toJson(Gson.java:648)
                                                                   at com.google.gson.Gson.toJson(Gson.java:603)
                                                                   at com.google.gson.Gson.toJson(Gson.java:583)
                                                                   at com.quickblox.auth.session.b.save(Unknown Source)
                                                                   at com.quickblox.auth.session.QBSessionManager.setActiveSession(Unknown Source)
                                                                   at com.quickblox.auth.session.QBSessionJsonParser.extractEntity(Unknown Source)
                                                                   at com.quickblox.auth.session.QBSessionJsonParser.extractEntity(Unknown Source)
                                                                   at com.quickblox.core.parser.QBJsonParser.parse(Unknown Source)
                                                                   at com.quickblox.auth.session.Query$VersionEntityCallback.completedWithResponse(Unknown Source)
                                                                   at com.quickblox.auth.session.Query.completedWithResponse(Unknown Source)
                                                                   at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(Unknown Source)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                   at android.os.Looper.loop(Looper.java:207)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5736)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)

**Comment by tatanka987** [comment]
@ashutoshgohil looks like you use external Gson library(not from QuickBlox Android SDK). Gson library version 2.8.1 has issue with serialization null Date. You can use version 2.8.0 of Gson library or you can use Gson library from our SDK.

**Comment by tatanka987** [comment]
the snippet below demonstrate how to exclude Gson library from our SDK and connect external Gson library (code from build.gradle file of sample-core module):

dependencies {
    compile ("com.quickblox:quickblox-android-sdk-messages:$rootProject.qbSdkVersion") {
        exclude group: 'com.google.code.gson', module: 'gson'
    }

    compile 'com.google.code.gson:gson:2.8.0'
    ...
}

**Comment by loredan** [comment]
I'll just put it out here, my guess is, the issue comes from the fact that QBSession has tokenExpirationDate, when server does not return it in session.json, which makes it null and causes NullPointerException when writing it in storage. I don't know, structure just seems quite similar

**Comment by tatanka987** [comment]
Gson library (version 2.8.1) has issue with parsing null Date, check your version of Gson library in External libraries in Android Studio and replace it to 2.8.0 as I said above. Please see [screenshot](https://gyazo.com/5e8cdd995e7e33695483fc80093199c1)

**Comment by abdulmalekDery** [comment]
@tatanka987  How can I use your Gson library from your SDK?
