### ISSUE TITLE
Exception on File Upload, quickbloxVer = "3.11.0"

### ISSUE THREAD

**Issue by alllohaaa** [QuickBlox/quickblox-android-sdk-releases#29]
```
                                         java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                         	at java.text.SimpleDateFormat.parseInternal(SimpleDateFormat.java:1768)
                                         	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1755)
                                         	at java.text.DateFormat.parse(DateFormat.java:387)
                                         	at com.quickblox.auth.session.Query.parseExpirationDate(Unknown Source:9)
                                         	at com.quickblox.auth.session.Query$VersionEntityCallback.completedWithResponse(Unknown Source:38)
                                         	at com.quickblox.auth.session.Query.completedWithResponse(Unknown Source:11)
                                         	at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(Unknown Source:46)
                                         	at android.os.Handler.dispatchMessage(Handler.java:106)
                                         	at android.os.Looper.loopOnce(Looper.java:226)
                                         	at android.os.Looper.loop(Looper.java:313)
                                         	at android.app.ActivityThread.main(ActivityThread.java:8669)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by alllohaaa** [comment]
and this is 3.12.0

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at java.text.SimpleDateFormat.parseInternal(SimpleDateFormat.java:1738)
       at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1725)
       at java.text.DateFormat.parse(DateFormat.java:360)
       at com.quickblox.auth.session.Query.parseExpirationDate(Query.java:9)
       at com.quickblox.auth.session.Query$VersionEntityCallback.completedWithResponse(Query.java:32)
       at com.quickblox.auth.session.Query.completedWithResponse(Query.java:11)
       at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(HttpRequestRunnable.java:46)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by krishnapriya-zoftsolutions** [comment]
Facing the same error in react native sdk on file upload.
